[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[program.devnet]
boilerplate = "GCJacRTHfbCRPvDibuQBcznnuHS4qonfWr821wfR9hcd"

[provider]
cluster = "localnet"
wallet = "./config/id.json"

[scripts]
test = "./node_modules/ava/entrypoints/cli.mjs --timeout=10m"